INSERT INTO question (content) VALUES
('Qual é o principal protocolo de comunicação utilizado para transferência de arquivos entre computadores em uma rede?'),
('Qual é a linguagem de programação amplamente utilizada para o desenvolvimento web e que utiliza HTML e CSS'),
('O que significa a sigla "URL" em termos de navegação na web?'),
('Qual é o propósito do comando "git clone" no controle de versionamento Git?'),
('O que é o HTML em uma página web?'),
('O que é um loop em programação?'),
('Qual é a diferença entre HTTP e HTTPS?'),
('O que é um algoritmo?'),
('Qual é a função do comando "git push" no Git?'),
('O que é a programação orientada a objetos?'),
('Qual é a finalidade do CSS em uma página web?'),
('O que é um firewall?'),
('Qual é a diferença entre linguagens de programação de alto nível e baixo nível?'),
('O que é um servidor web?'),
('O que é uma variável em programação?'),
('O que é um sistema de controle de versão?'),
('Qual é a diferença entre JavaScript e Java?'),
('O que é um DNS?'),
('Qual é a diferença entre linguagens de programação interpretadas e compiladas?'),
('O que é SQL e para que é comumente utilizado?');